import { Metadata} from "next";
import './globals.scss'
import Link from "next/link";
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Staffchange',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body
      className={inter.className}
    >
    <Link href='/about'>About</Link>
    <Link href='/'>Home</Link>
      {children}
    </body>
    </html>
  )
}
